Display first iteration of FS metadata

diff --git a/trivialfs_gen b/trivialfs_gen
--- a/trivialfs_gen
+++ b/trivialfs_gen
@@ -1,24 +1,61 @@
-#! /bin/sh -e
-trap 'echo "Failed!" >& 2' 0
-t=`tempfile`
-exec 5> "$t"
-rm -- "$t"
+#! /bin/sh
+HDR_KEY=TrivialFS
+HDR_VAL=80a29844-f5e3-11e3-b1c1-b827eb896db5
+
+cleanup() {
+	for t in "$T" "$T2"
+	do
+		test -n "$t" && rm -- "$t"
+	done
+	test -n "$OK" || echo "Failed!" >& 2
+}
+
+set -e
+OK=; T=; T2=
+trap cleanup 0
+FSUUID=
+while getopts tru: OPT
+do
+	case $OPT in
+		u) FSUUID=$OPTARG;;
+		r | t) FSUUID=`uuidgen -$OPT`;;
+		*) fail
+	esac
+done
+shift `expr $OPTIND - 1`
+test -z "$FSUUID" && FSUUID=`uuidgen -r`
+T=`tempfile`; T2=`tempfile`
 find -type f -o -type l | cut -d / -f2- | LC_ALL=C sort \
 | while IFS= read -r fn
 do
 	stat -Lc "%i |%n" -- "$fn"
 done | sort -sn -k2 | {
+	out() {
+		test -z "$li" && return
+		local f size
+		f=${fn%%|*}
+		test -f "$f"
+		size=`stat -c %s -- "$f"`
+		echo "$start,$size=$fn"
+		cat "$f" >> "$T2"
+		start=`expr $start + $size`
+	}
+	cat <<- .
+	$HDR_KEY=$HDR_VAL
+	UUID=$FSUUID
+.
+	start=0
 	li=
 	while read -r i n
 	do
 		if test x"$li" != x"$i"
 		then
-			test -n "$li" && printf "%s\n" "$fn"
-			li=$i; fn=${n#?}
+			out; li=$i; fn=${n#?}
 		else
 			fn=$fn$n
 		fi
 	done
-	test -n "$li" && printf "%s\n" "$fn"
-} #>& 5
-trap - 0
+	out
+	echo EOF
+} #> "$T"
+OK=Y
